build = {
  {
    "core.wad",
    { "bin/data/core/*.lua", "LUA", "", compressed = true },
  },
  {
    "drl.wad",
    { "bin/data/drl/help/*.hlp", "RAW", "help",
      compressed = true, encoded = true },
    { "bin/data/drl/ascii/*.asc", "RAW", "ascii",
      compressed = true, encoded = true },
    { "bin/data/drl/fonts/font*.png", "IMAGE", "fonts" },
    { "bin/data/drl/fonts/default", "RAW", "fonts" },
    { "bin/data/drl/*.lua", "LUA", "",
      compressed = true, encoded = true },
    { "bin/data/drl/levels/**.lua", "LUA", "levels",
      compressed = true, encoded = true },
    { "bin/data/drl/items/*.lua", "LUA", "items",
      compressed = true, encoded = true },
    { "bin/data/drl/graphics/*.png", "IMAGE", "graphics" },
    { "bin/data/drl/sound/*.wav", "RAW", "sound", compressed = true },
    { "bin/data/drl/music/*.ogg", "RAW", "music" },
    { "bin/data/drl/music/*.mp3", "RAW", "music" },
    { "bin/data/drl/music/*.mid", "RAW", "music", compressed = true },
  },
}
